version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: docsearch-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: document_search
    networks:
      - docsearch-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: docsearch-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./documents:/app/documents
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/document_search?authSource=admin
      - DB_NAME=document_search
      - CORS_ORIGINS=http://localhost:3000,http://localhost
    depends_on:
      - mongodb
    networks:
      - docsearch-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docsearch-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - docsearch-network

  nginx:
    image: nginx:alpine
    container_name: docsearch-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - docsearch-network

volumes:
  mongodb_data:
  documents:

networks:
  docsearch-network:
    driver: bridge